frase = 'Silvio Jose da Silva'
print('escrever usando a posição : {}'.format(frase[5]))
print('Apresentar o primeiro caracter de uma mini cadeia de caracter: {}'.format(frase[9:13]))
print('Para selecionar de 2 em 2 caracteres: {}'.format(frase[9:21:2]))
print('Selecionar em uma posição inicial sem saber á ultima: {}'.format(frase[15:]))
print('Selecionar de 3 em 3 com uma posição inicial sem  posição final: {}'.format(frase[12::3]))
print('Tamanho de string e quantas existem: {}'.format(len(frase)))
print('Contar quantas vezes temos uma letra: {}'.format(frase.count('o')))
print('Contar quantas vezes temos uma letra obedendo uma ordem: {}'.format(frase.count('o',0,13)))
print('Contar quantas vezes ele vai ser encontrado na frase e onde ele começou: {}'.format(frase.find('Jose')))
print('Procurando frase errada: {}'.format(frase.find('android')))
print('Usando operador in para verificar a existençia: {}'.format('Silvio' in frase))
#Transformação
print('Fazer subistuição de uma frase existente na cadeia por uma nova frase: {}'.format(frase.replace('Jose','Joseph')))
print('Colocar em maiúscula: {}'.format(frase.upper()))
print('Colocar em minúsculo: {}'.format(frase.lower()))
print('Colocar a primeira letra em miúscula e o resto em minúscula: {}'.format(frase.capitalize()))
print('Colocar todas as primeira letras em miúscula e o resto em minúscula: {}'.format(frase.title()))
print('Remover espaços mau digitados >>>    O jogo é hoje  <<<   --> {}'.format('    O jogo é hoje  '.strip()))
print('Remover espaço a direita >>> O jogo é hoje  <<< --> {}'.format('O jogo é hoje'.rstrip()))
print('Remover espaço á esquerda >>>    O jogo é hoje <<< --> {}'.format('O jogo é hoje'.lstrip()))
print('Divisão de string: {}'.format(frase.split()))
print('Junção de strings: {}'.format(' '.join(frase)))